### ISSUE TITLE
how to add owlcarousel

### ISSUE THREAD

**Issue by jasminvdev** [breezefront/module-breeze#66] opened 2024-03-15 08:05 UTC
i add breeze module
apply configuration
than after 
home page owlcarousel is not working
please I need you help

**Comment by vovayatsyuk** [comment] 2024-03-15 09:30
OwlCarousel requires jQuery. Breeze doesn't use jQuery, so it will not work.

I recommend trying out built-in slider: https://breezefront.com/docs/slider#slider

**Comment by vovayatsyuk** [comment] 2024-03-15 09:31
Closing this issue, since it's not a bug. Use [discussions](https://github.com/orgs/breezefront/discussions) for any kind of questions please.

**Closed by vovayatsyuk** 2024-03-15 09:31 UTC
